In [1]:
import pandas as pd
import numpy as np
import h5py

In [2]:
test = h5py.File('output_name', 'r')

In [3]:
list(test.keys())

['data', 'nodes', 'sensors']

In [4]:
list(test['nodes'].keys())

['axis0',
 'axis1',
 'block0_items',
 'block0_values',
 'block1_items',
 'block1_values']

In [8]:
back_again = pd.read_hdf('output_name','nodes')

In [9]:
back_again

,node_id,project_id,vsn,address,lat,lon,description,start_timestamp,end_timestamp
0,001e0610ba46,AoT_Chicago,004,State St & Jackson Blvd Chicago IL,41.878377,-87.627678,AoT Chicago (S) [C],2017/10/09 00:00:00,NaN
1,001e0610ba3b,AoT_Chicago,006,18th St & Lake Shore Dr Chicago IL,41.858136,-87.616055,AoT Chicago (S),2017/08/08 00:00:00,NaN
2,001e0610f02f,AoT_Chicago,00A,Lake Shore Drive & Fullerton Ave Chicago IL,41.926261,-87.630758,AoT Chicago (S) [CA],2018/05/07 00:00:00,NaN
3,001e0610ba8f,AoT_Chicago,00D,Cornell & 47th St Chicago IL,41.810342,-87.590228,AoT Chicago (S),2017/08/08 00:00:00,NaN
4,001e0610ba16,AoT_Chicago,010,Homan Ave & Roosevelt Rd Chicago IL,41.866349,-87.710543,AoT Chicago (S) [C],2018/07/18 00:00:00,NaN
...,...,...,...,...,...,...,...,...,...
121,001e06118433,AoT_Chicago,10E,ComEd Training Center,41.829806,-87.659467,AoT Chicago (S) [CP] {ComEd},2019/04/25 00:00:00,NaN
122,001e061183bf,AoT_Chicago,11A,ComEd Training Center,41.829806,-87.659467,AoT Chicago (S) [CP] {ComEd},2019/04/25 00:00:00,NaN
123,001e0611804d,AoT_Chicago,11E,ComEd Training Center,41.829806,-87.659467,AoT Chicago (S) [CP] {ComEd},2019/04/25 00:00:00,NaN
124,001e061182a2,AoT_Chicago,13B,ComEd Training Center,41.829806,-87.659467,AoT Chicago (S) [CP] {ComEd},2019/04/25 00:00:00,NaN
125,001e061144be,AoT_Chicago,890,"UChicago, Regenstine Chicago IL",41.792543,-87.600008,AoT Chicago (S) [C] {UChicago},2018/03/15 00:00:00,NaN